better styling, errors

diff --git a/cfmt b/cfmt
--- a/cfmt
+++ b/cfmt
@@ -5,14 +5,22 @@
 # 3. moves files in tmp folder to current folder
 # 4. removes tmp folder
 
-TMP=/tmp/astyle-fmt/
+TMP="/tmp/astyle-fmt/"
+
+OPT="--recursive --indent-col1-comments --delete-empty-lines --max-code-length=80 --break-after-logical"
 
 mkdir -p $TMP
 
 for f in $@
 do
 	mkdir -p $TMP"$(dirname "$f")"
-	astyle < $f > $TMP$f
-	mv $TMP$f $f
+	astyle $OPT < $f > $TMP$f
+	if [ $? == 0 ]
+		then
+			mv $TMP$f $f
+		else
+			echo "error: no files were altered."
+			break # exits loop
+	fi
 done
 rm -rf $TMP
